# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
