# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171215_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Place'),
        ),
    ]
